### ISSUE TITLE
BaristaIconDataBase.dat not updating

### ISSUE THREAD

**Issue by LushoM** [wiiu-env/homebrew_on_menu_plugin#22]
The BaristaIconDataBase.dat file on the SD doesn't update, neither does the MLC one, so it hides the titles in the Daily Log.

The only way for it to update, is to start with Tiramisu and start the title and then go back to Aroma.

**Comment by Maschell** [comment]
Can you confirm this is fixed with https://github.com/wiiu-env/homebrew_on_menu_plugin/releases/tag/homebrew_on_menu_plugin-20230321-113005 ?

**Comment by jamescrzb** [comment]
Yes, now all games are recorded in the daily log without showing "Other titles".
Thank you so much.
