### ISSUE TITLE
[FEATURE REQUEST] maskable apps

### ISSUE THREAD

**Issue by jabba80** [wiiu-env/homebrew_on_menu_plugin#23]
After installing Retroarch on my WiiU (aroma beta6) I had about 3-5 pages full of channels ( 107 retroarch cores as channel-symbols to be precise).

As probably this is not the only case where one doesn't want all apps in the Channel-Menu, how about evaluating a .ignore file (or similar) to skip certain apps?

**Comment by Maschell** [comment]
Implemented with #30 

See:
https://github.com/wiiu-env/homebrew_on_menu_plugin/releases/tag/homebrew_on_menu_plugin-20230321-180133
