### ISSUE TITLE
[Enhancement] Ability to hide all RPX files regardless if they have wuhb equivalent

### ISSUE THREAD

**Issue by DraconicNEO** [wiiu-env/homebrew_on_menu_plugin#25]
Self Explanatory, I think there should be an option to hide all rpx files whether or not they have a wuhb equivalent in case the user would rather hide all their rpx homebrew from the menu, rather than replacing it all with wuhb homebrew.

**Comment by Maschell** [comment]
Implemented with https://github.com/wiiu-env/homebrew_on_menu_plugin/commit/dc80552d5f108e0108926356da328a1dc34b71dc. 

Latest nightly can be downloaded here:
https://github.com/wiiu-env/homebrew_on_menu_plugin/releases
